### ISSUE TITLE
Auto play? Wtf

### ISSUE THREAD

**Issue by Lokua** [waud/waud#12]
I'm not alone in the opinion that a webpage should not automatically start playing audio, even if it is solely audio or even web audio related. Perhaps you will reconsider the website design and add a giant, very noticeable, play button in the banner? Users do not like being out of control, and this made me scramble to turn the volume off (and I'm a lifelong electronic musician and web audio enthusiast) / not because of what was playing, but when and where.

**Comment by Lokua** [comment]
...and how

**Comment by adireddy** [comment]
Coming from the gaming background, I am used to playing audio on page load but it could be annoying to some users.

Removed autoplay now. Thanks for the feedback.
