### ISSUE TITLE
No "ua" element

### ISSUE THREAD

**Issue by OpenGrid** [waud/waud#13]
element id="ua" doesn't exist on the page

**Comment by adireddy** [comment]
can you elaborate pls, not sure what you mean

**Comment by jeffskelton3** [comment]
I think @OpenGrid is referring to the javascript demo page in the README not playing. Just checked it out myself and was getting this error: `Uncaught TypeError: Cannot read property 'play' of undefined` in chome dev tools. I tracked it down to a `document.getElementById("ua")` call thats returning null.

Thanks for putting this together by the way. Looks very promising.

**Comment by adireddy** [comment]
Thanks again @jeffskelton3 

Fixed `ua` issue and the demo page works fine now.
