### ISSUE TITLE
[FYI] waud.js now available through cdn

### ISSUE THREAD

**Issue by maml** [waud/waud#16]
Now vailable via cdn:
* cdnjs page - https://cdnjs.com/libraries/waud.js
* was added as a result of cdnjs's issue [#8907](https://github.com/cdnjs/cdnjs/issues/8907).

**Comment by maml** [comment]
Just saw your updated README, looks like you know this already. Sry for the noise.

**Comment by adireddy** [comment]
Awesome. Thank you @maml 👍

**Comment by adireddy** [comment]
Noticed it yesterday but thank you anyway :)

**Comment by maml** [comment]
Nice nice, yeah they make it super-easy to request new libs (via issues) so I submitted one the other day.
