### ISSUE TITLE
[fyi] duration always returns undefined

### ISSUE THREAD

**Issue by maml** [waud/waud#17]
`duration` is [documented as a property](http://www.waudjs.com/api/classes/WaudSound.html#property_duration) on WaudSound but when I attempt to read it, it's always `undefined`. I am able to get it though by using the `get_duration` method.

I'm using `https://cdnjs.cloudflare.com/ajax/libs/waud.js/0.7.3/waud.min.js`.

**Comment by adireddy** [comment]
To make it consistent removed `duration` property and added `getDuration()` methiod in v0.7.4
