### ISSUE TITLE
Breaking change for WaudBase64Pack in minor version

### ISSUE THREAD

**Issue by johanlajili** [waud/waud#19]
Hi, since the 0.7.8 they are breaking changes. After investigation, it turns out the **WaudBase64Pack** constructor now has a different signature,
from
url, onLoaded, onProgress, onError
to
url, options, onLoaded, onProgress, onError

This is a breaking change and should be made either retro-compatible or a major version.

**Comment by adireddy** [comment]
fixed in 0.7.9
