### ISSUE TITLE
Support of IOS 6.x

### ISSUE THREAD

**Issue by johanlajili** [waud/waud#20]
Hello, Waudjs is crashing on IOS 6.x, when you try to access noteGrainOn

```haxe
if (start >= 0 && end > -1) {
    if (Reflect.field(source, "start") != null) source.start(0, start, end);
    else {
        untyped __js__("this._snd").noteGrainOn(0, start, end);
    }
} else {
    if (Reflect.field(source, "start") != null) source.start(0, _pauseTime, source.buffer.duration);
    else untyped __js__("this._snd").noteGrainOn(0, _pauseTime, source.buffer.duration);
    source.loop = _options.loop;
}
```

Right now you check if **.start** is available, otherwise you follow **.noteGrainOn**, but **.noteGrainOn** is itself the newer version of the even more deprecated **.noteOn**. You should add an extra check for that.

**Comment by adireddy** [comment]
If I remember correctly `noteGrainOn` should work in iOS6. However, the problem here is something else. `this._snd` should be `this.source` which I missed in my earlier refactor.

Will fix it and also add another condition for noteOn just in case.

**Comment by johanlajili** [comment]
Oh make sense. Looking forward to the update.

**Comment by adireddy** [comment]
done, can you check and let me know

**Comment by johanlajili** [comment]
working thanks
