### ISSUE TITLE
!isLoaded false when using base64

### ISSUE THREAD

**Issue by karneaud** [waud/waud#22]
So I have the following code

```
player = new WaudSound(audios[$scope.directionCount]);
player.play();
```
where `audios[$scope.directionCount]` is an array of base64 strings. 

The problem occurs when I `player.play()` but do not get the expected results but instead get

> sound not loaded

not sure why this is occurring as there is no need to load the sound

**Comment by adireddy** [comment]
The problem here is even though the base64 string is local and no loading involved, there is still a decoding process involved `AudioContext.decodeAudioData` to decode the audio data.

To automatically play the sound immediately, you can use `autoplay` property.

```
player = new WaudSound(audios[$scope.directionCount], {autoplay:true});
```

**Comment by karneaud** [comment]
@adireddy oooohhhh... will try this what I had to do for some reason was

```
player.load(function(){ player.play(); }); 
```

and got it to work.
