### ISSUE TITLE
Sound stops on screen lock in iOS

### ISSUE THREAD

**Issue by sedubois** [waud/waud#23]
Hi! Thanks for your work :) I wanted to check your library, especially how it runs on my iPhone 6 (iOS 10.3.1), but when loading waudjs.com in Safari, going to "Player" section, loading the sounds, and hitting play, the sound starts playing but then stops if I lock the phone screen. 

How can this be prevented?
Thanks a lot

**Comment by adireddy** [comment]
Hey @sedubois, Maybe I have enabled `autoMute` in the player sample I need to check the code but anyway you can continue listening to the audio when you lock the screen when `autoMute` is not enabled.

You can check the following samples on your phone.

http://www.waudjs.com/radio/
http://www.waudjs.com/sample/

Let me know the outcome.

**Comment by sedubois** [comment]
Thanks, tried http://www.waudjs.com/radio/ and that works :) 

Does this use HTML5 on iOS? Because Caniuse says that iOS supports Web Audio API: http://caniuse.com/#feat=audio-api

I'll try to make more complex tests such as delayed playback and combinining several audios in a sequence (needed for my meditation timer) when I get a chance.

**Comment by adireddy** [comment]
Radio uses HTML5 as live streams can only be played through HTML5 Audio. But the second sample URL uses Web Audio API. I checked both the samples to make sure :)

**Comment by sedubois** [comment]
Yes when playing the "No Auto Stop Web Audio" button from http://www.waudjs.com/sample on my phone, the sound stops when locking the screen.

Thanks for the explanations! Basically I can't use web audio API, only HTML5.
