### ISSUE TITLE
Question: Does waud support volume fading?

### ISSUE THREAD

**Issue by brenwell** [waud/waud#25]
Hello team waud, I have been searching around for an alternative to Howler.js and from the Api docs it appears that all functionality I need is also available in Waud except fading. Is this supported or is there a way to do it easily that you could share. 

Thanks alot

**Comment by adireddy** [comment]
Hi @brenwell, fading is not supported in waud atm. Will look into adding that functionality soon. Alternatively, you can maybe use `setInterval` and gradually increase/decrease volume property of the sound.

**Comment by brenwell** [comment]
Thanks for the swift response.

Sounds good, I am building games, so perhaps I could use my tweening library to interpolate the values in the meantime.

An additional feature request, which i wouldn't expect you to pursue but will ask anyway, is to play sequences. Howler doesn't have this feature either but i built a functionality ontop of howler. It simply plays one track after another with a callback at the end, and returns a function to stop the sequence. If you think there is enough demand, I would certianly use it.

```js
const winLadder = ['win-ladder-1','win-ladder-2','win-ladder-3']
const stopFunction = Sound.playSequence(winLadder, () => console.log('Finished'))
stopFunction();
```

Anyway thanks again
