### ISSUE TITLE
Resume doesn't work in Firefox

### ISSUE THREAD

**Issue by 3vilguy** [waud/waud#26]
Hello again :)
Looks like there is some inconsistency with pause and resume in Firefox.
So going to [sample page](http://www.waudjs.com/sample/) in Chrome or Safari and playing with Test1/Test2 (they have Pause button) you can `Pause` a sound and then clicking `Play` continues from the place it was paused. So it basically works like a resume.
In Firefox however, clicking `Play` doesn't resume, but play the sound from the start.

Best Regards

**Comment by adireddy** [comment]
Firefox is triggering `onend` event where everything will be reset. Will add a hack fix for that but not sure if it will break anything else.

**Comment by 3vilguy** [comment]
Thanks Adi. Will let you know if I notice any weird behavior anywhere else.
