### ISSUE TITLE
Explorer11-waud not working

### ISSUE THREAD

**Issue by oshratk87** [waud/waud#28]
Hi,
I'm using with Waud (version 0.9.12) for my audio service,
I run the application with angular2
Waud initial by this function:
 load(extention?:string, route?:string): Observable<Function> {
    return Observable.create(observable => {
        Waud.init();
        Waud.enableTouchUnlock(this.touchUnlock);
        //Waud.autoMute();

        let thisScope = this;
        var audioUrl = _AUDIOURL_;

        this.instance = new WaudSound(audioUrl, {
            onload: function (a: WaudSound) {
                observable.next();
                observable.complete();
            },
            onerror: function (a: WaudSound) {
                thisScope.loggerService.error('Waud: Error loading Asset: ' + audioUrl);
                observable.next();
                observable.complete();
            }
        });
    });
} 

private touchUnlock() {
    //Touch unlock event for iOS devices
    if (!this.instance.isPlaying()) this.play('');
} 

//spriteName="sndButton"
play(spriteName?: string, soundProps?: AudioSpriteSoundProperties) {
   if (spriteName) this.instance.play(spriteName + 'Sound', soundProps);
      else this.instance.play();
}

and when I run it in Explorer11,

on call to play() from line 1187:
return (__map_reserved[spriteName] != null ? _this1.getReserved(spriteName) :_this1.h[spriteName]).play(spriteName,soundProps);

I get the error in play function at line 307:
this._snd.currentTime = this._pauseTime == null ? soundProps.start : this._pauseTime;

in console.log the values are:
this._snd.currentTime = 0
 this._pauseTime=undefined
soundProps.start=812

and the error is
ERROR InvalidStateError
ERROR InvalidStateError
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      ABORT_ERR: 20,
      code: 11,
      constructor: { },
      DATA_CLONE_ERR: 25,
      DOMSTRING_SIZE_ERR: 2,
      HIERARCHY_REQUEST_ERR: 3,
      INDEX_SIZE_ERR: 1,
      INUSE_ATTRIBUTE_ERR: 10,
      INVALID_ACCESS_ERR: 15,
      INVALID_CHARACTER_ERR: 5,
      INVALID_MODIFICATION_ERR: 13,
      INVALID_NODE_TYPE_ERR: 24,
      INVALID_STATE_ERR: 11,
      message: "InvalidStateError",
      name: "InvalidStateError",
      NAMESPACE_ERR: 14,
      NETWORK_ERR: 19,
      NO_DATA_ALLOWED_ERR: 6,
      NO_MODIFICATION_ALLOWED_ERR: 7,
      NOT_FOUND_ERR: 8,
      NOT_SUPPORTED_ERR: 9,
      PARSE_ERR: 81,
      QUOTA_EXCEEDED_ERR: 22,
      SECURITY_ERR: 18,
      SERIALIZE_ERR: 82,
      SYNTAX_ERR: 12,
      TIMEOUT_ERR: 23,
      TYPE_MISMATCH_ERR: 17,
      URL_MISMATCH_ERR: 21,
      VALIDATION_ERR: 16,
      WRONG_DOCUMENT_ERR: 4
   } 

I hope you will find a solution for this issue
Thanks!

**Comment by adireddy** [comment]
do you have this running somewhere where I can test?

**Comment by oshratk87** [comment]
Hi
I hope that next week I will have an external link for the project that you
can test
thanks,
Oshrat

2017-09-12 18:50 GMT+03:00 Adi <notifications@github.com>:
