### ISSUE TITLE
Incomplete build of waud.js in dist folder

### ISSUE THREAD

**Issue by StephanGerbeth** [waud/waud#29]
Hi,

i had some problems to load and run waud.js by webpack.

Code:
```
import Waud from 'waud.js';
Waud.Waud.init();
var base64pack = new Waud.WaudBase64Pack("/dev/assets/sounds.json", _onLoad);
function _onLoad(snds) {
    snds.get('test.wav');
}
```
Result:
> Uncaught TypeError: snds.get is not a function

At first I thought the import of the library won't work probably. (https://github.com/waud/waud/issues/21). But I compared the waud.js files in your sample-folder (https://github.com/waud/waud/blob/dev/sample/waud.js) and dist-folder and realized that they are different.

When I use the waud.js file of your sample-folder everything works fine. But the waud.js file in your dist-folder seems to be broken. There is no get-function inside the returned Object and so on. 

Could you check your dist-folder and fix it, please?
Thanks Stephan

**Comment by adireddy** [comment]
can you try again with the new release @StephanGerbeth

**Comment by StephanGerbeth** [comment]
Hi,

version 0.9.13 works.

```
import {Waud, WaudBase64} from 'exports-loader?Waud=global.Waud,WaudBase64=global.WaudBase64Pack!waud.js';

Waud.init();
new WaudBase64("/dev/assets/sounds.json", function(sounds) {
    sounds.get('test.wav').play();            
});
```
Thanks!

PS: Wish for the future - perhaps you can wrap your code inside a universal modul definition. so the loading of your lib is easier in a wepack environment.

**Comment by adireddy** [comment]
hey @StephanGerbeth I don't have much experience with webpack but FYI just tried the following and it works fine

```
import {waudjs} from "waud.js"

Waud.init();
new WaudSound("assets/countdown.mp3", { onload: function(snd) {
    snd.play();
}});

new WaudBase64Pack("assets/sounds.json", function(sounds) {
    sounds.get('test/countdown.mp3').play();
});
```

Also works with require

```
var waudjs = require("waud.js");
```
