### ISSUE TITLE
Takes very long time before playing the mp3

### ISSUE THREAD

**Issue by roshangm1** [waud/waud#30]
Hi,
For playing a music online, when webaudio is enabled takes very long time. I think, it's downloading the mp3 file first and then playing. 
When disabling webaudio, it worked fine on Desktop but not on any mobile devices. Mobile Devices won't play anything i guess even after the user interaction.

**Comment by adireddy** [comment]
Hi @roshangm1, how big is the sound? Is it possible to send me the sound so that I can do some tests when I get a chance?

**Comment by roshangm1** [comment]
It's the regular mp3 song of around ~5mb hosted online. I ended up using the html5 audio tag for this.
